### ISSUE TITLE
2 errors/ typos in readme

### ISSUE THREAD

**Issue by flomock** [mheinzinger/SeqVec#1]
in the first line it should be:
from allennlp.comman**d**s.elmo import ElmoEmbedder
instead of your version without the d

and you give the ElmoEmbedder the parameter in the wrong order, it should be:
seqvec = ElmoEmbedder(**options,weights**,cuda_device=0)

would be nice if you fix this

**Comment by sacdallago** [comment]
Thanks for the heads up, on it

**Comment by mheinzinger** [comment]
Thanks for notifying! Fixed.
