### ISSUE TITLE
Is it possible to embed batched sequences?

### ISSUE THREAD

**Issue by ufimtsev** [mheinzinger/SeqVec#2]

**Comment by mheinzinger** [comment]
Yes, it is possible and actually it is crucial to make max. usage of your VRAM and to speed up embeddings. All you need to do is use elmo.predict_on_batches( List[ List[str] ]). It takes a list of lists as input, with the inner list being a list of words/amino acids.
You can check the official implementation here: https://github.com/allenai/allennlp/blob/master/allennlp/commands/elmo.py

**Comment by mheinzinger** [comment]
If you sort your sequences according to their length before embedding them, you can increase speed further.
