### ISSUE TITLE
Checkpoint file for the SeqVec model

### ISSUE THREAD

**Issue by ashishjain1988** [mheinzinger/SeqVec#5]
Can you please point me where I can find the final checkpoint files for the SeqVec protein embedding model.

**Comment by sacdallago** [comment]
https://github.com/mheinzinger/SeqVec/issues/3#issuecomment-512879661

**Comment by ashishjain1988** [comment]
@sacdallago Thanks for the comment, but that issue consists of the checkpoints files for the classification models (right?). I have some new protein sequences and want to retrain the SeqVec embedder. Can you please point to which specific checkpoint files should I use for that?

**Comment by sacdallago** [comment]
To retrain the embedder, you have to train an [Elmo](https://allennlp.org/elmo) model. There are no checkpoints for retraining, just parameters. For the set of parameters used @mheinzinger can help you out.

The point of the embedder is that you don't have to retrain it whenever you have a bunch of new sequences! This will be very expensive, and for a few new sequences w.r.t. the large databases (e.g. uniref90) it won't change the internal state of the model by much.

If you want to _embed_ the new sequences, you have to use the checkpoint of the elmo embedder as described in the readme.

**Comment by mheinzinger** [comment]
Just catching up here; sorry for the long delay. Checkpoint files are now available here:
rostlab.org/~deepppi/seqvec_checkpoint.tar.gz
Would be interesting to hear your experience with fine-tuning the model if possible :)

**Comment by ashishjain1988** [comment]
Thank you for the files!
